### ISSUE TITLE
incompatible fields errors

### ISSUE THREAD

**Issue by shumiyao** [officialrajdeepsingh/contentLayerNetlifycms#1]
I have tried your repo, but I got bunch of errors with "incompatible fields", which results with no document generated.

```
 └── 28 documents contain field data which didn't match the structure defined in the document type definition. (Skipping documents)
"article-post-16.md" of type "Post" has the following incompatible fields:
       • tags: "neovim" 

...

Generated 0 documents in .contentlayer
```

If I change the following in the `contentlayer.config.ts`  file

```
      categories:{
        type: 'list',of: Categories,
      }
```

to:

```
        categories: {
            type: 'list', of: { type: 'string' },
        }
```

It seems to work. But is this how it is supposed to be?

**Comment by officialrajdeepsingh** [comment]
Now everything is fine, and you can use it.

**Comment by shumiyao** [comment]
@officialrajdeepsingh 

Thank you very much for taking a moment. Wish you a nice day!
